### ISSUE TITLE
Missing Imports

### ISSUE THREAD

**Issue by svsjo** [DHBW-Inf20/Sort-Benchmarker#1]
Wollte mir das Spiel mal anschauen und habe daher das Repos geclont. Dann läuft jedoch nichts, da einige Imports fehlen. 
Eine Jar zum so ausführen konnte ich auch nicht finden. @FabiKl help
Falls ihr auch wie wir nur den Repos Link abgegeben habt, fixt das noch schnell - evtl. haben sie sich das noch nicht angeschaut

Edit: Es geht nach hinzufügen von von junit, was intelliJ erkennt. Jedoch ist weiterhin alles rot markiert, warum auch immer. Testet es am besten mal selbst
![image](https://user-images.githubusercontent.com/79276639/132514398-07264024-e866-4ea1-a28d-ebd96c8961a4.png)

**Comment by Fabi-02** [comment]
Danke für die Info, also wir haben den Code als zip und ne Ausführbaren Datei geschickt und nicht unsere repo.
Aber, dass es nachdem junit hinzugefügt wurde immer noch nicht funktioniert ist mir rätselhaft.
Könntest du vlt (falls noch alles rot ist) mal die Ordnerstruktur von dem Projekt schicken. So wie es auf dem Screenshot aussieht findet es die eigenen Dateien nicht unter dem Pfad.

**Comment by svsjo** [comment]
Hat sich, warum auch immer, von selbst gelöst. 
Funktioniert hat es sowieso, jedoch war weiterhin alles rot. Jetzt aber nicht mehr, idk warum - ist auch egal xD
